### ISSUE TITLE
サイクル分割

### ISSUE THREAD

**Issue by zmogials213** [katamine-lab-2024/one-log-docs#5]
# 07-04

中村
高橋

- [x] 各サイクルでやることをきめる

## 成果物

[サイクル分割](https://mailkyutechjp-my.sharepoint.com/:x:/g/personal/nakamura_yuki148_mail_kyutech_jp/EWQpl4nFpGZFvhOr91fzDiEB7rlpDBoj8PmS_nwsAT7-2A?e=iljETo)

# 今後すること

- #6
-  #4

**Comment by yuki6ra** [comment]
優先度から考える？
そもそもの要求から考えた方が良い？

当初のサイクル

<img width="553" alt="スクリーンショット 2024-07-04 15 39 31" src="https://github.com/katamine-lab-2024/one-log-docs/assets/111046707/c1176993-2294-41ae-a673-bdd73b8afa6d">

**Comment by yuki6ra** [comment]
TSPiによると
- 最初は時間短めになる方が良い
- 同じ機能が分割されないように

**Comment by yuki6ra** [comment]
# 第2サイクル

## 機能
- ログを計測
- デイリーレポートのガワ
  - 画面だけは作っておく（拡張性のために）
  - ログ情報の確認のために、ログ情報の表示のみ

## DBテーブルについて

- ログテーブル
- ユーザーテーブル
- カテゴリテーブル

**サインアップ・サインイン**機能が完成するまで、adminユーザー(test用ユーザー)を登録して使用する

## 時間

216.67時間
1人当たりの1週間の作業量を7時間とすると(演習以外に時間を割くことになるので)、
217 / (7 * 2)
= 15.5週

**Comment by yuki6ra** [comment]
時間がやばすぎるので、共通UIは必要最低限以外は作成しない
~この時点で約9週間(一人あたり週14時間)
一人当たり7時間だと、約19週~

**Comment by yuki6ra** [comment]
# 第3サイクル

## 機能

- ログ編集削除
- デイリーレポート中身

- 共通UI諸々

## 時間

198.33時間
198 / 14 = 14
14.2週

**Comment by yuki6ra** [comment]
エクスポート機能はレポート画面完成後
どのデータをエクスポートするのか考えやすいので

**Comment by zmogials213** [comment]
サイクル3

- 
-

**Comment by yuki6ra** [comment]
# 第4サイクル

## 機能

- リマインド
- サインアップ
- サインイン

## 時間


254 / 14 = 18
18週

**Comment by yuki6ra** [comment]
# 第5サイクル

## 機能

- 週間レポート
- 月間レポート

## 時間

288時間
288 / 14 = 20.6
20.6週

**Comment by yuki6ra** [comment]
# 第6サイクル

## 機能

- カテゴリレポート
- エクスポート

## 時間

173 / 14 = 12.4
12.4週

**Comment by yuki6ra** [comment]
全部足したら80.7週になるはず
なった👍

<img width="670" alt="スクリーンショット 2024-07-04 17 45 05" src="https://github.com/katamine-lab-2024/one-log-docs/assets/111046707/bc108ba5-1e71-46b7-9098-a2cc8b2f5946">

1年半のプロジェクトに...

**Comment by yuki6ra** [comment]
# 07-05ゼミ

- [ ] サイクル1の成果物を考慮した時間見積もりをしよう
- サイクル2は完成させたい気持ちがあるのなら、週の稼働時間を増やしても良い
- [ ] サイクルを経るごとに慣れがでてLOC/Hourは増えるはず

https://github.com/katamine-lab-2024/one-log-docs/issues/3#issuecomment-2209919447
https://github.com/katamine-lab-2024/one-log-docs/issues/6#issuecomment-2209964916
