### ISSUE TITLE
成果物分析

### ISSUE THREAD

**Issue by zmogials213** [katamine-lab-2024/one-log-docs#6]
# 07-04
### 要求分析
 - 背景と目的　⇒　要求と目的、機能がつながらない（レポートの表示に関して）
 - 用語定義　　⇒　定義が不十分（リマインド）
 - 機能要件　　⇒　OK（要求に対して機能は網羅されていた。）
 - データ要件　⇒　OK（ログのデータ要件がすべてある。）
 - 技術要件　　⇒　OK（この技術要件で実現可能なことは確認済み。

### 基本設計
 - アーキテクチャ構成図　⇒　OK（各構成要素がわかる。それら関係もわかる）
 - 画面設計　　　　　　　⇒　画面遷移や、画面構成の定義ができていない　　　　　　　　　　　　　　　　　　　
 - 機能毎のシーケンス図　⇒　ログをとる機能、レポート機能にトークン検証処理
 　　　　　　　　　　　　　  を加える必要がある

**Comment by yuki6ra** [comment]
# 07-05ゼミ

- [ ] 各成果物が「どれくらいの時間かけたか」まで分析
→ 概念設計、時間見積もりで完成した成果物分を考慮しやすいよね

https://github.com/katamine-lab-2024/one-log-docs/issues/3#issuecomment-2209919447
https://github.com/katamine-lab-2024/one-log-docs/issues/5#issuecomment-2209936394
